import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Manrope } from "next/font/google";
import QueryProvider from "@/components/provider/QueryProvider";
import { Toaster } from "sonner";
import SessionWrapper from "@/components/provider/SessionProvider";

// Global font (Poppins)
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

// Additional font (Manrope for h2)
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Grati Swag",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/fav.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${manrope.variable}`}>
      <body className="antialiased">
        <QueryProvider>
         <SessionWrapper>{children}</SessionWrapper>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
